### PR TITLE
Check data length

### PR DESCRIPTION
**Pull request by anti-social**
Fixes index out of bounds error when parsing invalid data

### CODE REVIEW

**Comment by tact1m4n3** [comment]
I just pushed a heavily refactored version of the project. I've noticed that this new version does not panic when parsing invalid data. I might be wrong tho... I haven't done much testing yet

**Comment by anti-social** [comment]
I'd rather return an error instead of coercing to the maximum value:
```
let len = (u8::from_le(data[1]) as usize + 2).min(Packet::MAX_LENGTH)
```
So if you are OK with that I will refactor the PR

**Comment by anti-social** [comment]
> I've noticed that this new version does not panic when parsing invalid data

It returns `InvalidType { raw_type: 0 }` error instead. So it perceives third byte in a buffer as a packet type. It does not panic due to a static buffer length.

**Comment by anti-social** [comment]
Have a question. Why do you wrap bytes from a buffer in some sites into `u8::from_le`? Technically it is a no-op for any architecture.

**Comment by tact1m4n3** [comment]
Hey. Yeah I agree with you that we should return an error. But don’t start refactoring just yet, because I plan to change a lot of things like today(or tomorrow) :))

**Comment by tact1m4n3** [comment]
> Have a question. Why do you wrap bytes from a buffer in some sites into `u8::from_le`? Technically it is a no-op for any architecture.

Really? Aren’t there architectures using big endian?

**Comment by anti-social** [comment]
> Really? Aren’t there architectures using big endian?

But it is a single byte. It only does things for number types like `u16`, `i16`, `u32` etc. I think `from_le`, `from_be`, `swap_bytes` are just methods that all number types have for consistency.

**Comment by tact1m4n3** [comment]
I think endianness affects single bytes as well as it dictates if you read from left or right those 8 bits

**Comment by anti-social** [comment]
> Hey. Yeah I agree with you that we should return an error. But don’t start refactoring just yet, because I plan to change a lot of things like today(or tomorrow) :))

Sorry, did not have time to read your comment

**Comment by anti-social** [comment]
> I think endianness affects single bytes as well as it dictates if you read from left or right those 8 bits

Endianness is about a byte order, not bit

**Comment by tact1m4n3** [comment]
It’s fine as I haven’t changed anything yet

**Comment by anti-social** [comment]
And you can simply check it:

```
assert_eq!(u8::from_le(0xef), 0xef);
assert_eq!(u8::from_be(0xef), 0xef);
```

**Comment by anti-social** [comment]
Found an answer: https://github.com/rust-lang/rust/issues/44724#issuecomment-344188069

**Comment by tact1m4n3** [comment]
You’re right. I had it wrong :))

**Comment by tact1m4n3** [comment]
Then, as you said, there is no need for those

> Have a question. Why do you wrap bytes from a buffer in some sites into `u8::from_le`? Technically it is a no-op for any architecture.

**Comment by tact1m4n3** [comment]
Is there anything more you would like to add? I was thinking of making a release soon.

**Comment by anti-social** [comment]
> Is there anything more you would like to add? I was thinking of making a release soon.

I would like to have a possibility to process all addresses. For example to be able to sniff packets between a transmitter and a handset.

**Comment by anti-social** [comment]
We could have 2 constructors for the parser: `new` and `new_with_address`

**Comment by anti-social** [comment]
You can say we can create multiple parsers: one to parse packets from a handset and the other to parse data from a transmitter. But a handset and a transmitter use half-duplex uart via single wire.

**Comment by tact1m4n3** [comment]
I went for a single address since that address would already be known to the user. If a parser parses packets with multiple addresses then we need a way of returning that address. maybe return it in a tuple with the packet

**Comment by tact1m4n3** [comment]
image
Something like this

**Comment by tact1m4n3** [comment]
Actually maybe it is better to create a new method like next_packet_with_address for that. What do you think?

**Comment by anti-social** [comment]
> Actually maybe it is better to create a new method like next_packet_with_address for that. What do you think?

TBH I don't like adding a lot of similar methods

**Comment by anti-social** [comment]
Returning tuple is OK for me

**Comment by tact1m4n3** [comment]
alright.

**Pull request merged**
